-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               10.6.7-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for deep rock galactic
CREATE DATABASE IF NOT EXISTS `deep rock galactic` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `deep rock galactic`;

-- Dumping structure for table deep rock galactic.build
CREATE TABLE IF NOT EXISTS `build` (
  `build_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `build_name` varchar(50) NOT NULL DEFAULT '0',
  `build_author` varchar(50) NOT NULL DEFAULT '0',
  `build_description` varchar(200) NOT NULL DEFAULT '0',
  `dwarf_id` int(10) unsigned NOT NULL DEFAULT 0,
  `grenade_id` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`build_id`),
  KEY `FK1_dwarf_id_dwarf` (`dwarf_id`),
  KEY `FK2_grenade_id_grenade` (`grenade_id`),
  CONSTRAINT `FK1_dwarf_id_dwarf` FOREIGN KEY (`dwarf_id`) REFERENCES `dwarf` (`dwarf_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK2_grenade_id_grenade` FOREIGN KEY (`grenade_id`) REFERENCES `grenade` (`grenade_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.build: ~0 rows (approximately)
/*!40000 ALTER TABLE `build` DISABLE KEYS */;
/*!40000 ALTER TABLE `build` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.build_equipment
CREATE TABLE IF NOT EXISTS `build_equipment` (
  `build_id` int(10) unsigned NOT NULL,
  `equipment_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`build_id`,`equipment_id`),
  KEY `FK_build-equipment_equipment` (`equipment_id`),
  CONSTRAINT `FK_build-equipment_build` FOREIGN KEY (`build_id`) REFERENCES `build` (`build_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_build-equipment_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `equipment` (`equipment_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.build_equipment: ~0 rows (approximately)
/*!40000 ALTER TABLE `build_equipment` DISABLE KEYS */;
/*!40000 ALTER TABLE `build_equipment` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.build_overclock
CREATE TABLE IF NOT EXISTS `build_overclock` (
  `build_id` int(10) unsigned NOT NULL,
  `overclock_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`build_id`,`overclock_id`),
  KEY `FK_build-overclock_overclock` (`overclock_id`),
  CONSTRAINT `FK_build-overclock_build` FOREIGN KEY (`build_id`) REFERENCES `build` (`build_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_build-overclock_overclock` FOREIGN KEY (`overclock_id`) REFERENCES `overclock` (`overclock_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.build_overclock: ~0 rows (approximately)
/*!40000 ALTER TABLE `build_overclock` DISABLE KEYS */;
/*!40000 ALTER TABLE `build_overclock` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.build_perk
CREATE TABLE IF NOT EXISTS `build_perk` (
  `build_id` int(10) unsigned NOT NULL,
  `perk_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`build_id`,`perk_id`),
  KEY `FK_build-perk_perk` (`perk_id`),
  CONSTRAINT `FK_build-perk_build` FOREIGN KEY (`build_id`) REFERENCES `build` (`build_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_build-perk_perk` FOREIGN KEY (`perk_id`) REFERENCES `perk` (`perk_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.build_perk: ~0 rows (approximately)
/*!40000 ALTER TABLE `build_perk` DISABLE KEYS */;
/*!40000 ALTER TABLE `build_perk` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.build_upgrade
CREATE TABLE IF NOT EXISTS `build_upgrade` (
  `build_id` int(10) unsigned NOT NULL,
  `upgrade_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`build_id`,`upgrade_id`),
  KEY `FK_build-upgrade_upgrade` (`upgrade_id`),
  CONSTRAINT `FK_build-upgrade_build` FOREIGN KEY (`build_id`) REFERENCES `build` (`build_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_build-upgrade_upgrade` FOREIGN KEY (`upgrade_id`) REFERENCES `upgrade` (`upgrade_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.build_upgrade: ~0 rows (approximately)
/*!40000 ALTER TABLE `build_upgrade` DISABLE KEYS */;
/*!40000 ALTER TABLE `build_upgrade` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.dwarf
CREATE TABLE IF NOT EXISTS `dwarf` (
  `dwarf_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dwarf_name` varchar(50) DEFAULT NULL,
  `dwarf_desc` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`dwarf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.dwarf: ~4 rows (approximately)
/*!40000 ALTER TABLE `dwarf` DISABLE KEYS */;
INSERT INTO `dwarf` (`dwarf_id`, `dwarf_name`, `dwarf_desc`) VALUES
	(1, 'Driller', 'A digging specialist who can carve through rock with ease with his Titanium Powerdrills'),
	(2, 'Engineer', 'A tactical Dwarf who excels in area control with his Sentry Turrets and Platform Gun.'),
	(3, 'Gunner', 'A front-line combatant armed with a terrifyingly powerful Minigun which can mow down targets with ease, and a Zipline Gun for crossing large gaps and inclines.'),
	(4, 'Scout', 'The most mobile of the four Dwarves with his Grappling Hook carrying him to any height and his Flare Gun illuminating even the grimmest of caves.');
/*!40000 ALTER TABLE `dwarf` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.equipment
CREATE TABLE IF NOT EXISTS `equipment` (
  `equipment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `equipment_name` varchar(50) DEFAULT NULL,
  `equipment_type` enum('primary','secondary','mobility','support','armor') DEFAULT NULL,
  `num_tiers` tinyint(4) DEFAULT NULL,
  `equipment_desc` varchar(400) DEFAULT NULL,
  `dwarf_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`equipment_id`),
  KEY `FK1_equipment_dwarf` (`dwarf_id`),
  CONSTRAINT `FK1_equipment_dwarf` FOREIGN KEY (`dwarf_id`) REFERENCES `dwarf` (`dwarf_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.equipment: ~32 rows (approximately)
/*!40000 ALTER TABLE `equipment` DISABLE KEYS */;
INSERT INTO `equipment` (`equipment_id`, `equipment_name`, `equipment_type`, `num_tiers`, `equipment_desc`, `dwarf_id`) VALUES
	(1, 'CRSPR Flamethrower', 'primary', 5, 'When bullets or blunt force just don\'t cut it, a sea of roaring, sticky napalm usually does. Practically never explodes in your face.', 1),
	(2, 'Cryo Cannon', 'primary', 5, 'Mad geniuses have tried perfecting this implement for as long as anyone can remember, but our lads at R&D seem to have perfected it! Handily portable (for a dwarf, anyway), it does exactly what you think: It\'s a friggin\' freeze ray. Let \'em have it.', 1),
	(3, 'Corrosive Sludge Pump', 'primary', 5, 'The Corrosive Sludge Pump is what happens when the maintenance staff are left with too much time on their hands. A complicated network of piping, distillation bottles, and safety valves results in a very capable device indeed - lobbing globs of toxic waste at those you disapprove of has never been so fun!', 1),
	(4, 'Subata 120', 'secondary', 5, 'A small, light semi-automatic for small, light dwarves. More deadly than it appears.', 1),
	(5, 'Experimental Plasma Charger', 'secondary', 5, 'Bullets are so last year. Instead, why not incinerate your enemies from the inside out with a highly experimental anti-matter-powered gun firing supercharged plasma bolts? What\'s the worst that could happen? (If you find out, please report to R&D)', 1),
	(6, 'Reinforced Power Drills', 'mobility', 4, 'One of the classic workhorses of DRG, the twin-linked Power Drill makes short work of more or less anything unfortunate enough to be in front of it. That includes your teammates, mind', 1),
	(7, 'Satchel Charge', 'support', 4, 'Be it an obstacle or a particularly thickheaded adversary, a good ol\' Satchel Charge usually gets the job done. Stand well back before hitting the trigger.\r', 1),
	(8, 'Mole Armor Rig', 'armor', 4, 'The "Mole" Armor Rig is the Driller\'s piece of undersuit armor. It can be upgraded to improve its resistance against fire damage.', 1),
	(9, 'Warthog Auto 210', 'primary', 5, 'Living up to its name, this pig of a weapon never fails to satisfy. Holds six wide-spread shells for rapid-fire death dealing.', 2),
	(10, 'Stubby Voltaic SMG', 'primary', 5, 'So what\'s better than an SMG? An SMG that fires ELECTRIC BULLETS! The boys in R&D have wired a prototype ArcGen into the guts of this trusty Subata 312, meaning it now unleashes a storm of electrified DEATH! Word of warning: Keep away from water.\r', 2),
	(11, 'LOK-1 Smart Rifle', 'primary', 5, 'Take a standard, high-grade submachine gun, bolt a semi-sentient AI Core to the side of it, and rig it up with several sophisticated tracking packages. Arm that resulting abomination with prototype rounds that interface directly with the onboard systems, and you have the aptly named LOK-1 Smart Rifle - a glorious bit of kit any Engineer worth their salt would be happy carrying.', 2),
	(12, 'Deepcore 40mm PGL', 'secondary', 5, 'Whoever coined the phrase "Bang for the Buck" must have had this lovely thing in mind. Cheap, dependable, and utterly devastating.\r', 2),
	(13, 'Breach Cutter', 'secondary', 5, 'The Breach Cutter releases directional blasts of sonically-charged plasma powerful enough to deal with most any alien in your path. Originally a mining tool, it\'s now been frequency-tuned to crack open flesh and bone rather than the sediment deposits it was designed for - often with quite spectacular results!\r', 2),
	(14, 'Platform Gun', 'mobility', 3, 'It does what it says on the box. By firing a combination of highly volatile chemicals at a nearby wall, the result is a rapidly solidifying concrete-like foam that can support several tons of weight. Do not ingest!\r', 2),
	(15, 'LMG Gun Platform', 'support', 4, 'One of the more advanced items in the DRG arsenal, these autonomous sentry guns will absolutely help in performing pest control.\r', 2),
	(16, 'Owl Armor Rig', 'armor', 4, 'The "Owl" Armor Rig is the Engineer\'s piece of undersuit armor. It can be upgraded to improve its resistance against hazardous poison.', 2),
	(17, 'Lead Storm Powered Minigun', 'primary', 5, 'What\'s more effective than bullets? A whole LOT of bullets. With a fire rate of more than 3500 rounds per minute, the Minigun remains a mainstay of any heavy engagement.', 3),
	(18, 'Thunderhead Heavy Autocannon', 'primary', 5, 'A peculiar but devastating weapon. The slow rate of fire is made up for by heavy damage, delivered with glee by the belt-fed .50-caliber tungsten rounds. The Thunderhead is a somber weapon for the sophisticated executioner, delivering death as inexorably as the passage of time itself.', 3),
	(19, 'Hurricane Guided Rocket System', 'primary', 5, 'The Hurricane has quickly gotten a reputation for being a very crowd-pleasing weapon - unless we\'re talking about the crowd it is being aimed at. It stows a weapons package usually reserved for heavy-duty tripods into something a hearty dwarf can carry with ease and has even been upgraded with sophisticated tracking software.', 3),
	(20, 'Bulldog Heavy Revolver', 'secondary', 5, 'A custom revolver firing rounds so large it only holds 4 shots. More or less nothing can stand before a direct hit from one of these 26mm monstrosities.', 3),
	(21, 'BRT7 Burst Fire Gun', 'secondary', 5, 'More precise than an SMG, with the stopping power of a small shotgun, the BRT (or "Burt", as it\'s sometimes called) is highly prized among collectors and connoisseurs alike.', 3),
	(22, 'Zipline Launcher', 'mobility', 3, 'Fully portable and constructed from lightweight components, this handy gadget will fire a steel-reinforced tether across any chasm you might happen upon in the depths.', 3),
	(23, 'Shield Generator', 'support', 3, 'Projects an energy bubble that simultaneously keeps you reasonably safe from harm while recharging your shield. Comfortably fits a full team inside! Don\'t get too comfy, however... the effects do not last long.\r', 3),
	(24, 'Barracuda Armor Rig', 'armor', 4, 'Each set of DRG issue armor is mounted on a highly modifiable undersuit, capable of transforming the capabilities of the armor considerably. Regrettably, R&D has as yet proven unable to utilize the suit\'s stillsuit capacity towards onboard production of alcohol.', 3),
	(25, 'Deepcore GK2', 'primary', 5, 'A dependable, hefty weapon. Usually not the first choice of proper Dwarves, but the combination of heft, weight, and satisfying boom makes it worthwhile all the same.', 4),
	(26, 'M1000 Classic', 'primary', 5, 'The original design for the M1000-pattern DRG-issue precision rifle goes back hundreds of years, practically unchanged. High damage, respectable fire rate...and that "Ping". A prime example of "if it ain\'t broke, don\'t fix it".', 4),
	(27, 'DRAK-25 Plasma Carbine', 'primary', 5, 'The DRAK-25 is among the newest additions to the DRG arsenal and is a bit of a technological marvel. Capable of laying down a blistering hail of superheated plasma without hardly ever blowing up in your hands, AND comparatively cheap to manufacture, Management were quick to approve and sign off on this design.', 4),
	(28, 'Jury-Rigged Boomstick', 'secondary', 5, 'You take a shotgun and cut it in half. You\'re left with a light handcannon that handles like a large pistol and has the stopping power of an 18-wheeler loaded with watermelons. A true classic.\r', 4),
	(29, 'Zhukov NUK17', 'secondary', 5, 'Never sophisticated, but never disappointing either. The NUK family of twinned micro SMGs has a long and treasured track record, yet Those In The Know generally agree that the 17 is among the very best\r', 4),
	(30, 'Grappling Hook', 'mobility', 4, 'The ultimate explorer\'s tool - this self-recharging grappling hook will get you out of any sticky situation, and onto any distant ledge. Handle with care - ending up dangling from the ceiling and then dropping 60 feet onto the floor is not covered by the employee insurance.\r', 4),
	(31, 'Flare Gun', 'support', 3, 'A powerful projectile launcher that shoots high-intensity, adhesive flares. The flares can attach to even the hardest material.', 4),
	(32, 'Fox Armor Rig', 'armor', 4, 'The "Fox" Armor Rig is the Scout\'s piece of undersuit armor. It can be upgraded to improve its resistance against fall damage.', 4);
/*!40000 ALTER TABLE `equipment` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.grenade
CREATE TABLE IF NOT EXISTS `grenade` (
  `grenade_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `grenade_name` varchar(50) DEFAULT NULL,
  `grenade_desc` varchar(400) DEFAULT NULL,
  `dwarf_id` int(10) unsigned DEFAULT 0,
  PRIMARY KEY (`grenade_id`),
  KEY `FK_grenade_dwarf` (`dwarf_id`),
  CONSTRAINT `FK_grenade_dwarf` FOREIGN KEY (`dwarf_id`) REFERENCES `dwarf` (`dwarf_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.grenade: ~12 rows (approximately)
/*!40000 ALTER TABLE `grenade` DISABLE KEYS */;
INSERT INTO `grenade` (`grenade_id`, `grenade_name`, `grenade_desc`, `dwarf_id`) VALUES
	(1, 'Impact Axe', 'The Impact Axe is the connoisseur choice for the dwarf of tomorrow. Compact and easy to carry, extends to full size upon throwing, and discharges a lethal burst of electricity upon impact with any living target. Can be safely retrieved by the user in case of bad aim.', 1),
	(2, 'High Explosive Grenade', 'A standard high-explosive grenade with a medium kill radius. Can be used to remove dirt or bugs or both.', 1),
	(3, 'Neurotoxin Grenade', 'Releases a cloud of slow-acting toxins engineered to exclusively affect life indigenous to Hoxxes IV. WARNING: HIGHLY FLAMMABLE!', 1),
	(4, 'L.U.R.E.', 'This Laser Utility Refraction Emitter - or L.U.R.E for short - projects a handsome hologram that will attract all nearby enemies. Be mindful to keep your distance - once the onboard shielding fails, it will unleash a devastating electrical charge.', 2),
	(5, 'Plasma Burster', 'The Plasma Burster does more or less what you\'d expect from the name. It releases 4 bursts of scorching plasma in rapid succession upon being thrown. Keep away from beards at all costs.', 2),
	(6, 'Proximity Mine', 'A timeless classic. Sticks to any surface and explodes shortly after an enemy enters its trigger area. And if it fails to find a target, it can be safely disarmed and retrieved. Note: proximity trigger requires a few seconds for calibration.', 2),
	(7, 'Sticky Grenade', 'Will stick to any surface or creature, and then explode after a short time. Sometimes keeping it simple is best.', 3),
	(8, 'Incendiary Grenade', 'One of our most popular "handle with care" items. Will explode on activation, covering a large area in roaring fire. Would almost be cozy if the flames did not burn hot enough to melt steel.', 3),
	(9, 'Cluster Grenade', 'When one grenade just won\'t cut it. This thing is basically Armageddon in the palm of your hand.', 3),
	(10, 'Inhibitor-Field Generator', 'The IFG - or Inhibitor-Field Generator- is one of the latest inventions of the good people down in R&D. Toss one of these bad boys into a cluster of bugs, and watch them slow right down.', 4),
	(11, 'Cryo Grenade', 'Instantly lowers the ambient temperature of everything in a medium-sized area. Will flash-freeze most Hoxxes wildlife - as well as any hapless DRG employees caught in the blast zone.', 4),
	(12, 'Pheromone Canister', 'Any creature covered by the substance within becomes an irresistible target to any kind of Hoxxes wildlife. Handle with extreme care. The boys in R&D are very proud of this one.', 4);
/*!40000 ALTER TABLE `grenade` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.overclock
CREATE TABLE IF NOT EXISTS `overclock` (
  `overclock_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `overclock_name` varchar(50) DEFAULT NULL,
  `overclock_type` enum('clean','balanced','unstable') DEFAULT NULL,
  `overclock_desc` varchar(400) DEFAULT NULL,
  `weapon_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`overclock_id`),
  KEY `FK_overclock_equipment` (`weapon_id`),
  CONSTRAINT `FK_overclock_equipment` FOREIGN KEY (`weapon_id`) REFERENCES `equipment` (`equipment_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=125 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.overclock: ~124 rows (approximately)
/*!40000 ALTER TABLE `overclock` DISABLE KEYS */;
INSERT INTO `overclock` (`overclock_id`, `overclock_name`, `overclock_type`, `overclock_desc`, `weapon_id`) VALUES
	(1, 'Lighter Tanks', 'clean', 'Lighter weight gear means more fuel and sandwiches.', 1),
	(2, 'Sticky Additive', 'clean', 'Special additive compound extends the Sticky Flame duration and increases direct damage.', 1),
	(3, 'Compact Feed Valves', 'balanced', 'The smaller mechanism allows for greater tank capacity and more fuel at the cost of reload speed and opperational range.', 1),
	(4, 'Fuel Stream Diffuser', 'balanced', 'Increases operation range but decreases the fuel flow rate.', 1),
	(5, 'Face Melter', 'unstable', 'This crazy bit of tweaking will give a big boost in damage and flow rate but at the cost of operational range and tank capacity.', 1),
	(6, 'Sticky Fuel', 'unstable', 'Special fuel mixture extends the duration and damage of Sticky Flames but at the cost of tank capacity and total fuel.', 1),
	(7, 'Improved Thermal Efficiency', 'clean', 'Get all you can from your fuel and lose pressure slower from the main chamber.', 2),
	(8, 'Tuned Cooler', 'balanced', 'Freeze things faster at the cost of a slower pump and turbine.', 2),
	(9, 'Flow Rate Expansion\n', 'balanced', 'A low volume high pressure chamber paired with a high power pump increase the flow rate and repressurization speed but lower the max duration of sustained flow.', 2),
	(10, 'Ice Spear', 'balanced', 'Pressing the reload button dumps all the fluid in the chamber directly into the turbine, flash freezing it and launching an ice projectile. Side effects include an increased recharge delay and of course the large amount of fuel used.', 2),
	(11, 'Ice Storm', 'unstable', 'A change in the fuel mixture along with some heavy cooler unit tweaks means a lot more damage especially to frozen targets. However, freezing takes longer and the capacity of the pressure chamber is reduced.', 2),
	(12, 'Snowball', 'unstable', 'Pressing the reload button shoots all the cryofuel in the chamber at once as an AoE cryo-projectile. Besides the very large amount of fuel consumed, the operation overloads the whole system resulting in a much longer delay before regaining pressure and the modifications restrict the total amount of fuel you can carry.', 2),
	(13, 'Hydrogen Ion Additive\n', 'clean', 'Experimental additive that activates on impact gives a small improvement to the corrosive DoT and slowdown effect of direct hits.', 3),
	(14, 'AG Mixture', 'clean', 'Anti-gravity pellets suspended in the sludge let the projectiles fly further and faster.', 3),
	(15, 'Volatile Impact Mixture\n', 'balanced', 'Special mixture increases immediate projectile damage at the cost of the long term corrosive and slowdown effects and puddle lifetime as the volatile compound evaporates much faster.', 3),
	(16, 'Disperser Compound', 'balanced', 'Charged shots break apart into more fragments on impact and each fragment is more potent, however the initial damage of the charged projectile impact is reduced.', 3),
	(17, 'Goo Bomber Special', 'unstable', 'The addition of finely tuned timed separation compounds cause the charged shots to leave a trail of sludge as they fly through the air. However the projectile depletes its mass as it flies, dealing less impact damage as fragments separate and completely expiring once all fragments are dropped.', 3),
	(18, 'Sludge Blast\n', 'unstable', 'The charged shot cohesion is disrupeted on firing, instantly shooting out fragments in a shotgun-like blast. While spectacular the modifications result in reduced magazine size and ammo capacity by an extented reload process.', 3),
	(19, 'Chain Hit', 'clean', '"Any shot that hits a weakspot has a high chance to ricochet into a nearby enemy."	\r', 4),
	(20, 'Homebrew Powder', 'clean', 'More damage on average but it\'s a bit inconsistent.', 4),
	(21, 'Oversized Magazine', 'balanced', 'Custom magazine that can fit a lot more ammo but it\'s a bit unwieldy and takes longer to reload.', 4),
	(22, 'Automatic Fire', 'unstable', 'Fully automatic action, watch out for the recoil.', 4),
	(23, 'Explosive Reload', 'unstable', 'Micro-explosives that explode inside hit targets when you reload. However these fancy bullets come at the cost of total ammo and magazine capacity.', 4),
	(24, 'Tranquilizer Rounds', 'unstable', 'Part bullet, part syringe these rounds are very effective at stunning most enemies.', 4),
	(25, 'Energy Rerouting', 'clean', 'A masterwork of engineering that improves charge speed and energy efficiency without affecting overall performance!', 5),
	(26, 'Magnetic Cooling Unit', 'clean', 'A high-tech solution to cleanly improve the cooling rate. The result is an increased number of shots that can be fired before overheating, a faster recovery from an overheat and an extended duration that a full charge can be maintained.', 5),
	(27, 'Heat Pipe', 'balanced', 'By channeling exhaust heat back into the charge chamber a shot can be charged faster while using less energy. Unfortunately this process generates a lot more heat.', 5),
	(28, 'Heavy Hitter', 'balanced', 'Some extensive tweaking to how the shots are prepared can increase the pure damage of the weapon but at the cost of more heat per shot and a reduced battery size.', 5),
	(29, 'Overcharger', 'unstable', 'Pushing the EPC to the limit will give you a significant increase in charge shot damage and a boost in the size of the explosion but at the cost of thermal efficiency and energy consumption.', 5),
	(30, 'Persistent Plasma', 'unstable', 'By changing how the plasma is layered within the charged projectile a slow and persistent discharge can be achieved upon impact. However this does reduce the instant damage done.', 5),
	(31, 'Stunner', 'clean', 'Heavier rounds allow for Stun chance on all body parts, not just weakpoints. Shooting already stunned enemies with this overclock will deal extra damage.', 9),
	(32, 'Light-Weight Magazines', 'clean', 'It\'s amazing how much material can be removed without affecting anything and lighter magazines means more magazines and faster reloading.', 9),
	(33, 'Magnetic Pellet Alignment', 'balanced', 'Electromagnets in the chamber greatly reduces shot spread and increases weakpoint damage at the cost of a slower rate of fire.', 9),
	(34, 'Cycle Overload', 'unstable', 'Heavy modification to the chamber greatly increases the maximum rate of fire and increases raw damage but reduces the weapon\'s accuracy and reload speed as a consequence.', 9),
	(35, 'Mini Shells', 'unstable', 'Smaller shells designed around a new charge type reduce recoil and increase overall ammo and magazine capacity at the cost of raw damage.', 9),
	(36, 'Super-Slim Rounds', 'clean', 'Same power but in a smaller package giving slightly better accuracy and letting you fit a few more rounds in each magazine.', 10),
	(37, 'Well Oiled Machine', 'clean', 'When you need a little more sustained damage.', 10),
	(38, 'EM Refire Booster', 'balanced', 'Use the electron circuit of the SMG to boost its fire rate and damage but the accuracy suffers as a result.', 10),
	(39, 'Light-Weight Rounds', 'balanced', 'They don\'t hit quite as hard, and can\'t handle fast fire rates but you sure can carry a lot more of them!', 10),
	(40, 'Turret Arc', 'unstable', 'Use the gemini turrets as nodes in an electric arc. Zap! The downside is less ammo and a slower rate of fire.', 10),
	(41, 'Turret EM Discharge', 'unstable', 'Shoot a turret to turn it into the epicenter of an electric explosion! The bullet modifications unfortunately also lower the direct damage and electrocution chance.', 10),
	(42, 'Eraser', 'clean', 'clean up the caves with an extended magazine combined with the ability to acquire more locks.', 11),
	(43, 'Armor Break Module', 'clean', 'Shots do extra damage against armor when all locks are engaged.', 11),
	(44, 'Explosive Chemical Rounds', 'balanced', 'Every enemy with 3 locks triggers an explosion on the last shot.', 11),
	(45, 'Seeker Rounds', 'balanced', 'Locked shots will always hit their target even finding their way around heavy armor and the system can maintain locks at more extreme angles. However the extra processing load reduces the rate of fire for locked shots and more care must be taken when reloading the advanced rounds.', 11),
	(46, 'Executioner', 'unstable', 'Tweaks to the firecontrol mechanism and camera software bring lightning fast lock acquisition and more weakspot damage when all locks are used, However the max number of locks is reduced as is the magazine and total ammo capacity.', 11),
	(47, 'Neuro-Lasso', 'unstable', 'Slow down enemies by locking on to them, the more locks the slower an enemy gets! The down side is a slower lock-on rate and the locks can only be maintained for a short time before the system resets.', 11),
	(48, 'Clean Sweep', 'clean', 'Increases the explosion radius and damage without any unwanted effects.', 12),
	(49, 'Pack Rat', 'clean', 'You found a way to pack away two more rounds somewhere.', 12),
	(50, 'Compact Rounds', 'balanced', 'Smaller and lighter rounds means more rounds in the pocket at the cost of the explosion\'s effective radius and damage.', 12),
	(51, 'RJ250 Compound', 'balanced', 'Use explosions to launch yourself and your teammates into the air.', 12),
	(52, 'Fat Boy', 'unstable', 'Big and deadly and dirty. Too bad plutonium is so heavy that you can only take a few rounds with you. And remember to take care with the fallout.', 12),
	(53, 'Hyper Propellant', 'unstable', 'New super-high velocity projectiles trade explosive range for raw damage in a tight area. The increased weight of the rounds also limits how many you can carry.', 12),
	(54, 'Light-Weight Cases', 'clean', 'Bring more ammo with you and slam those cases in faster!', 13),
	(55, 'Roll Control', 'clean', 'A few tweaks to the launcher cause it to add roll to the projectile after it is ejected thus covering a larger area as it travels. Holding down the trigger as the line leaves the gun activates a remote connection which on the release of the trigger cause the line to stop rolling letting you lock its orientation.', 13),
	(56, 'Stronger Plasma Current', 'clean', 'By improving the node\'s efficiency you can up the raw damage without too much fuss and it lasts a bit longer too!', 13),
	(57, 'Return to Sender', 'balanced', 'Holding down the trigger after the line leaves the gun activates a remote connection which on the release of the trigger causes the line to change direction and move back towards the gun.', 13),
	(58, 'High Voltage Crossover', 'balanced', 'By passing an electric current through the plasma, the beam electrocutes anything it touches but the bulky hardware limits magazine capacity.', 13),
	(59, 'Spinning Death', 'unstable', 'These modified plasma nodes convert most of the forward momentum into angular momentum stretching out the beam and continuously doing damage to the immediate area where it was launched. The nodes run for a longer duration but deal less damage every second. Due to the weight both magazine and total capacity is greatly reduced.', 13),
	(60, 'Inferno', 'unstable', 'Turn your Breach Cutter into a tool of burning death and destruction at the cost of ammo, and armor breaking. As a bonus the extreme internal heating keeps the targets burning for an extended period.', 13),
	(61, 'A Little More Oomph!', 'clean', 'Get the most out of each shot without compromising any of the gun\'s systems.', 17),
	(62, 'Thinned Drum Walls', 'clean', 'Stuff more bullets into the ammo drum by thinning the material in non-critical areas.', 17),
	(63, 'Burning Hell', 'balanced', 'Turn the area just infront of the minigun into an even worse place by venting all the combustion gasses forward. However, it does overheat rather quickly.', 17),
	(64, 'Compact Feed Mechanism', 'balanced', 'More space left for ammo at the cost of a reduced rate of fire.', 17),
	(65, 'Exhaust Vectoring', 'balanced', 'Increases damage at a cost to accuracy.', 17),
	(66, 'Bullet Hell', 'unstable', 'Special bullets that ricochet off all surfaces and even enemies going on to hit nearby targets. However they deal less damage and are less accurate overall.', 17),
	(67, 'Lead Storm', 'unstable', 'Pushing things to the limit this overclock greatly increases damage output at the cost of consistently stunning targets and the kickback makes it almost impossible to move.', 17),
	(68, 'Composite Drums', 'clean', 'Lighter weight materials means you can carry even more ammo!', 18),
	(69, 'Splintering Shells', 'clean', 'Specially designed shells splinter into smaller pieces increasing the splash damage range.', 18),
	(70, 'Carpet Bomber', 'balanced', 'A few tweaks here and there and the autocannon can now shoot HE rounds! Direct damage is lower but the increased splash damage and range lets you saturate an area like no other weapon can.', 18),
	(71, 'Combat Mobility', 'balanced', 'Fancy custom ammo drums improve weapon balance making it more accurate and easier to handle on the move while the improved feed motor increases the speed with which the max fire rate is reached. All this however comes at the cost of magazine capacity.', 18),
	(72, 'Big Bertha', 'unstable', 'Extensive tweaks give a huge bump in raw damage at the cost of ammo capacity and fire rate.', 18),
	(73, 'Neurotoxin Payload', 'unstable', 'Channel your inner war criminal by mixing some neurotoxin into the explosive compound. The rounds deal less direct damage and splash damage, but affected bugs move slower and take lots of damage over time.', 18),
	(74, 'Manual Guidance Cutoff', 'clean', 'New guidance system that disables missile guidance when the trigger is released. It\'s also lighter so the missiles can reach a higher top speed!', 19),
	(75, 'Overtuned Feed Mechanism', 'clean', 'With some slight tinkering, both your weapon and projectiles are faster.', 19),
	(76, 'Fragmentation Missiles', 'clean', 'With a thicker casing your missiles spread more fragments at higher speeds, increasing AoE efficiency', 19),
	(77, 'Plasma Burster Missiles', 'balanced', 'Turn the battlefield into a plasma apocalypse with these penetrating multi-burst missiles! They fly slower, don\'t hit as hard, and there is a limit to how many can be controlled at one time, but in the right hands even a single missile can do a lot of damage.', 19),
	(78, 'Minelayer System', 'balanced', 'When your missiles hit the ground they are planted as mines that explode when damaged or if enemies are in close proximity. Keep in mind that the new warheads do not have guidance. The total ammo capacity is also reduced.', 19),
	(79, 'Jet Fuel Homebrew', 'unstable', 'Grandpa\'s recipe. Highly unstable and heavy, but works like a charm! Your missiles get a much higher top speed and reach it instantly. The extra energy greatly improves direct damage but all that extra fuel reduces the missile payload capacity. Due to the extra weight both magazine and total ammo capacity are also reduced.', 19),
	(80, 'Salvo Module', 'unstable', 'Enables your weapon to load up to 9 missiles and launch them at once! As an added bonus the overloaded exhaust ports increase missile velocity and boost damage based on how many missiles are in the salvo. However the missiles in the salvo cannot be guided.', 19),
	(81, 'Chain Hit', 'clean', 'Any shot that hits a weakspot has a chance to ricochet into a nearby enemy.', 20),
	(82, 'Homebrew Powder', 'balanced', 'More damage on average but it\'s a bit inconsistent.', 20),
	(83, 'Volatile Bullets', 'balanced', 'Fuel on the fire! These rounds are extremely effective against burning targets but at the cost of direct damage dealt to unaffected creatures.', 20),
	(84, 'Six Shooter', 'balanced', 'An updated casing profile lets you squeeze 2 more rounds into the cylinder and take a few more rounds with you, but all that filling and drilling has compromised the accuracy of the weapon and it takes longer to reload.', 20),
	(85, 'Elephant Rounds', 'unstable', 'Heavy tweaking has made it possible to use modified autocannon rounds in the revolver! The damage is crazy but so is the recoil and you can\'t carry as many rounds. Also, only 3 rounds fit in the gun and reload time is a bit slower but base accuracy is improved.', 20),
	(86, 'Magic Bullets', 'unstable', 'Smaller, bouncy bullets ricochet off hard surfaces, hitting nearby enemies like magic! Overall, the damage of the weapon is reduced, but you can carry a few more rounds due to their compact size.', 20),
	(87, 'Composite Casings', 'clean', 'Lighter rounds that permit a shorter delay between bursts and you can carry a few more of them as well. What\'s not to like?', 21),
	(88, 'Full Chamber Seal', 'clean', 'Meticulous sealing lets you get a bit more power out of each round and the attention to detail improves how easily the magazine slots in.', 21),
	(89, 'Compact Mags', 'balanced', 'You can carry even more ammo but the rate of fire needs to be toned back to avoid a jam and please take more care while reloading.', 21),
	(90, 'Experimental Rounds', 'balanced', 'A new shape to the bullet delivers a lot more damage but it\'s odd size means fewer rounds in the clip and a bit less ammo overall.', 21),
	(91, 'Electro Minelets', 'unstable', 'After impacting terrain, these high-tech bullets convert in to electro-minelets that will electrocute anything unfortunate enough to come close. However they don\'t last forever and the rounds themselves take more space in the clip and deal less direct damage.', 21),
	(92, 'Micro Flechettes', 'unstable', 'Convert the BRT to fire small flechettes instead of slugs. Increases overall ammo and magazine size as well as reducing recoil but at the cost of raw damage.', 21),
	(93, 'Lead Spray', 'unstable', 'It ain\'t pretty but this overclock will tear apart anything that gets close, though it gets a bit iffy at range.', 21),
	(94, 'Compact Ammo', 'clean', 'Stuff a few more of these compact rounds into each magazine and they have a bit less recoil as well.', 25),
	(95, 'Gas Rerouting', 'clean', 'Increases the weapon\'s rate of fire without affecting performance and helps with magazine ejection as well.', 25),
	(96, 'Homebrew Powder', 'clean', 'More damage on average but it\'s a bit inconsistent.', 25),
	(97, 'Overclocked Firing Mechanism', 'balanced', 'More bullets faster and it kicks like a mule.', 25),
	(98, 'Bullets of Mercy', 'balanced', 'Deal bonus damage to burning, stunned, electrocuted, frozen, or poisoned targets.', 25),
	(99, 'AI Stability Engine', 'unstable', 'It\'s like it knows what you are going to do before you do it, compensating for all recoil and bullet spread. The system requires a lower rate of fire and the fin-stabilized rounds do less direct damage but give a bonus to weakpoint hits.', 25),
	(100, 'Electrifying Reload', 'unstable', 'Embedded capacitors electrocute targets from the inside when you reload. However all that tech reduces the raw damage of the bullets and takes up some space in the magazines.', 25),
	(101, 'Hoverclock', 'clean', 'Your movement slows down for a few seconds while using focus mode in the air.', 26),
	(102, 'Minimal Clips', 'clean', 'Increase clip capacity and speed up reloads by getting rid of dead weight on the clips.', 26),
	(103, 'Active Stability System', 'balanced', 'Focus faster and without slowing down but all that fancy tech limits how quickly you can reload.', 26),
	(104, 'Hipster', 'balanced', 'A less powerful round together with a rebalancing of weight distribution, enlarged vents and a reshaped grip result in a rifle that is more controllable when hip-firing in quick succession but at the cost of pure damage output. As an added bonus you can carry more of the new ammunition.', 26),
	(105, 'Electrocuting Focus Shots', 'unstable', 'Embedded capacitors in a copper core carry the electric charge from the EM coils used for focus shots and will electrocute the target at the cost of a reduced focus shot damage bonus.', 26),
	(106, 'Supercooling Chamber', 'unstable', 'Take the M1000\'S focus mode to the extreme by supercooling the rounds before firing to improve their acceleration through the coils, but the extra coolant in the clips limits how much ammo you can bring.', 26),
	(107, 'Impact Deflection', 'clean', 'Tinkering with the particle density makes your projectiles react on impact with armor and surfaces, making it bounce up to 2 times!', 27),
	(108, 'Thermal Liquid Coolant', 'clean', 'With a liquid coolant fitted to the weapons thermal system it transfers heat more efficiently, accelerating its cooling rate and reducing heat per shot.', 27),
	(109, 'Rewiring Mod', 'balanced', 'By rewiring the thermal systems into a secondary cell and connecting it to the primary battery, your weapon can convert the energy from overheating into ammo. However this reduces the maximum capacity of the primary battery significantly.', 27),
	(110, 'Aggressive Venting', 'balanced', 'Directional vents burn everything around you and send enemies running when the weapon overheats. It also reduces the overheat recovery time. Unfortunately the battery size has to be reduced and the passive cooling suffers as well.', 27),
	(111, 'Overtuned Particle Accelerator', 'unstable', 'The particle accelerator has been tuned way over safety standards to push the damage output to the limit! The modifications comes with a price to overall stability of the weapon and increased heat generation.', 27),
	(112, 'Shield Battery Booster', 'unstable', 'Plugging your shield directly into the weapon battery boosts the plasma feed and density significantly while at full shield and improves total ammo and rate of fire at all times. However the extra energy generates more heat and overheating the weapon will short circuit your shield.', 27),
	(113, 'Thermal Exhaust Feedback', 'unstable', 'Feeding the thermal exhaust back into the system transfers the heat generated after a 50% threshold to the plasma, making it increasingly hot. The modifications means more heat generated and it takes longer to get rid of during overheat.', 27),
	(114, 'Compact Shells', 'clean', 'You can carry a few more of these compact shells in your pockets and they are a bit faster to reload with.', 28),
	(115, 'Double Barrel', 'clean', 'Unload both barrels at once, no regrets.', 28),
	(116, 'Special Powder', 'clean', 'Less like gunpowder and more like rocketfuel, this mixture gives a hell of a kick that you can use to get places.', 28),
	(117, 'Stuffed Shells', 'clean', 'With a bit of patience and some luck you can get one more pellet and a few more grains of powder into each shell without affecting the gun\'s performance or losing an eye in the process.', 28),
	(118, 'Shaped Shells', 'balanced', 'Specially shaped shells result in a tighter shot but the number of pellets is reduced.', 28),
	(119, 'Jumbo Shells', 'unstable', 'These large shells pack a lot more charge for a big increase in damage but they also take up more space so total ammo is limited.', 28),
	(120, 'Minimal Magazines', 'clean', 'By filling away unnecessary material from the magazines you\'ve made them lighter, and that means they pop out faster when reloading. Also the rounds can move more freely increasing the max rate of fire slightly.', 29),
	(121, 'Custom Casings', 'balanced', 'Fit more of these custom rounds in each magazine but at small reduction in the rate of fire', 29),
	(122, 'Cryo Minelets', 'unstable', 'After impacting terrain, these high-tech bullets convert into cryo-minelets that will super-cool anything that comes close. However they don\'t last forever and the rounds themselves take more space in the clip and deal less direct damage.', 29),
	(123, 'Embedded Detonators', 'unstable', 'Special bullets contain micro-explosives that detonate when you reload the weapon at the cost of total ammo, magazine capacity and direct damage.', 29),
	(124, 'Gas Recycling', 'unstable', 'Special hardened bullets combined with rerouting escaping gasses back into the chamber greatly increases the raw damage of the weapon but makes it more difficult to control and removes any bonus to weakpoint hits.', 29);
/*!40000 ALTER TABLE `overclock` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.perk
CREATE TABLE IF NOT EXISTS `perk` (
  `perk_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `perk_name` varchar(50) DEFAULT NULL,
  `perk_type` enum('passive','active') DEFAULT NULL,
  `perk_desc` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`perk_id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.perk: ~22 rows (approximately)
/*!40000 ALTER TABLE `perk` DISABLE KEYS */;
INSERT INTO `perk` (`perk_id`, `perk_name`, `perk_type`, `perk_desc`) VALUES
	(1, 'Beast Master', 'active', 'Charm a Glyphid Grunt to become your loyal companion. You can only have one tamed Grunt at a time.(5 minute cooldown)\nTamed Grunts deal 300% more damage to their targets!'),
	(2, 'Berzerker', 'active', 'Go berzerk for 10 seconds during which you get boosted melee damage and a lightning-fast pickaxe Power Attack recharge.(4 minutes cooldown)'),
	(3, 'Dash', 'active', 'Get out of trouble with a short burst of speed.\nWhile dashing, you ignore all slowdown effects.(25 seconds cooldown)'),
	(4, 'Field Medic', 'active', 'You revive teammates 30% faster\nUpon reviving someone, nearby enemies flee!\nOnce per mission, you can get a downed teammate instantly back on their feet!'),
	(5, 'Heightened Senses', 'active', 'You get an early warning when a creature is about to grab you\n2 times per mission, you can escape after being grabbed, killing your captor in the process!(5 seconds cooldown)'),
	(6, 'Hover Boots', 'active', 'Fancy boots that let you hover in midair for 3.5 seconds.(75 seconds cooldown)'),
	(7, 'Iron Will', 'active', 'Never give up! Once per mission, get back into the fight with all your weapons reloaded and a rage-fueled strength for a 12 second last stand before going down for good!\nWhile in this state you move faster, hit harder, and are resistant to slowdowns.\nMake it count!'),
	(8, 'See You In Hell', 'active', 'Right after an enemy hits you with a melee attack you get a temporary melee damage bonus.\n3 times each mission, you can trigger a large neuro-pulse explosion after you go down. A residual neuro-electric field will electrocute and scare off enemies.(1 minute cooldown)\nNeuro-pulse radius increased!'),
	(9, 'Shield Link', 'active', 'Whenever you are within 4m of a teammate, both of your shields recharge 50% faster!\nYou can overcharge a teammate\'s shield to 300% for 30 seconds.(2 minutes cooldown)'),
	(10, 'Born Ready', 'passive', 'Unequipped weapons automatically reload after 5 seconds.'),
	(11, 'Deep Pockets', 'passive', 'Leave nothing behind! Each of your mineral pouches hold +15 more valuables!'),
	(12, 'Elemental Insulation', 'passive', 'Get 30% resistance to all elemental damage.'),
	(13, 'Friendly', 'passive', 'Through the power of friendship you both take and deal 50% less damage from friendly fire!'),
	(14, 'It\'s a Bug Thing', 'passive', 'For some reason, Loot Bugs explode whenever you get within 5m of them!'),
	(15, 'Resupplier', 'passive', 'You\'re a busy dwarf, got aliens to shoot!\r\nStock up on Ammo and Health 50% faster at the Resupply Pod.\r\nRegain an extra 25% health when you resupply!\r\nAfter resupplying, all weapons instantly reload!'),
	(16, 'Second Wind', 'passive', 'Get a 12% sprint speed boost.\r\nEffect activates after running for 4 seconds.'),
	(17, 'Strong Arm', 'passive', 'You throw flares with 50% more force than the average Dwarf! Woosh!\r\nGems and other heavy objects get a 20% bonus throwing force.'),
	(18, 'Sweet Tooth', 'passive', 'Getting a taste for that stuff! Get 30% more healing from consuming Red Sugar!\r\n20% movement speed bonus for 10 seconds after consuming Red Sugar!'),
	(19, 'Thorns', 'passive', 'Any time an enemy hits you with a melee attack it will itself take 24 damage.'),
	(20, 'Unstoppable', 'passive', 'Nothing holds you back! Environmental slow-down effects are reduced by 50%!\r\nYou move 25% faster while carrying heavy objects!'),
	(21, 'Vampire', 'passive', 'Good thing you work underground!\r\nRegain 5 health when you kill a medium sized or larger creature with a melee attack!'),
	(22, 'Veteran Depositor', 'passive', '"Expert bucket handling! You now deposit valuables into the MULE and Drop Pod 50% faster!\r\n30% Damage Reduction while within 7m of the MULE!"');
/*!40000 ALTER TABLE `perk` ENABLE KEYS */;

-- Dumping structure for table deep rock galactic.upgrade
CREATE TABLE IF NOT EXISTS `upgrade` (
  `upgrade_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `upgrade_name` varchar(50) DEFAULT NULL,
  `tier_number` tinyint(4) DEFAULT NULL,
  `upgrade_number` tinyint(4) DEFAULT NULL,
  `upgrade_desc` varchar(400) DEFAULT NULL,
  `equipment_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`upgrade_id`),
  KEY `FK_upgrade_equipment` (`equipment_id`),
  CONSTRAINT `FK_upgrade_equipment` FOREIGN KEY (`equipment_id`) REFERENCES `equipment` (`equipment_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=355 DEFAULT CHARSET=latin1;

-- Dumping data for table deep rock galactic.upgrade: ~354 rows (approximately)
/*!40000 ALTER TABLE `upgrade` DISABLE KEYS */;
INSERT INTO `upgrade` (`upgrade_id`, `upgrade_name`, `tier_number`, `upgrade_number`, `upgrade_desc`, `equipment_id`) VALUES
	(1, 'High Capacity Tanks', 1, 1, 'The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants.', 1),
	(2, 'High Pressure Ejector	', 1, 2, 'Increases the range of the flame for long distance incineration.', 1),
	(3, 'Unfiltered Fuel', 2, 1, 'The good folk in R&D have been busy. The overall damage of your weapon is increased.', 1),
	(4, 'Triple Filtered Fuel', 2, 2, 'Fire it up! You set things ablaze much faster. Time to watch the world burn...!', 1),
	(5, 'Sticky Flame Duration', 2, 3, 'Sticky flames duration increase', 1),
	(6, 'Oversized Valves', 3, 1, 'Increased fuel consumption rate for more damage', 1),
	(7, 'Sticky Flame Slowdown', 3, 2, 'Creatures moving through sticky flames are slowed', 1),
	(8, 'More Fuel', 3, 3, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 1),
	(9, 'It Burns!', 4, 1, 'A chance that your target will flee in terror for every second\r\nthat it is in your flame.', 1),
	(10, 'Sticky Flame Duration', 4, 2, 'Sticky flames duration increase.', 1),
	(11, 'More Fuel', 4, 3, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 1),
	(12, 'Heat Radiance', 5, 1, 'Burn everything around you', 1),
	(13, 'Targets Explode', 5, 2, 'Targets killed from direct damage have a chance to explode', 1),
	(14, 'Larger Pressure Chamber', 1, 1, 'Lets you shoot for a longer time before needing to refill the pressure chamber.', 2),
	(15, 'Faster Turbine Spinup', 1, 2, 'Start freezing things as soon as you pull the trigger with a near-instant turbine response.', 2),
	(16, 'Stronger Cooling Unit', 1, 3, 'Freeze things at a faster rate.', 2),
	(17, 'Larger Reserve Tank', 2, 1, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 2),
	(18, 'Overclocked Ejection Turbine', 2, 2, 'Increases the effective range of the weapon.', 2),
	(19, 'Bypassed Integrity Check', 2, 3, 'If you completely empty the pressure chamber, the weapon will immediately start repressurizing, safety be dammed!', 2),
	(20, 'Improved Pump', 3, 1, 'Refill the pressure chamber faster.', 2),
	(21, 'Increased Flow Volume', 3, 2, 'We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please.', 2),
	(22, 'Hard Mixture', 4, 1, 'Promotes Ice-crystal formation in the stream resulting in more direct damage.', 2),
	(23, 'Supercooling Mixture', 4, 2, 'Improves the heat capacity of the stream so you can freeze things at a faster rate.', 2),
	(24, 'Larger Reserve Tank', 4, 3, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 2),
	(25, 'Fragile', 5, 1, 'There is a chance that frozen targets will spontaneously shatter!', 2),
	(26, 'Cold Radiance', 5, 2, 'Any enemy that strays close to you while firing the Cryo Cannon will start to freeze.', 2),
	(27, 'High Capacity Tanks', 1, 1, 'The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants.', 3),
	(28, 'Better Air Pressurizer', 1, 2, 'The air pressurizer is improved, making the projectiles travel faster and further.', 3),
	(29, 'Air Sensitive Compound', 1, 3, 'When the goo is exposed to air it expands, making puddles cover a larger area on impact.', 3),
	(30, 'Dyse Nozzle', 2, 1, 'With the Dyse Nozzle your charged shot is launched with more force, making it damaging on impact.', 3),
	(31, 'Atomizer Nozzle', 2, 2, 'With the Atomizer Nozzle your charged shot will leave behind more fragments on impact.', 3),
	(32, 'Potent Goo Mix', 2, 3, 'Normal shots do more damage on impact.', 3),
	(33, 'Supersaturation', 3, 1, 'The goo goes through a process of supersaturation after impact, making the effects and puddles last longer.', 3),
	(34, 'More Goo Canisters', 3, 2, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 3),
	(35, 'Spillback Extension', 4, 1, 'With the Spillback Extension added to the nozzle you spend less goo when charging.', 3),
	(36, 'Improved Spooling Mechanism	', 4, 2, 'The spooling mechanism has been improved and can get you to a full charge faster!', 3),
	(37, 'Protein Disruption Mix', 5, 1, 'Disrupting the protein molecules in the goo mix has made it more rigid and harder for creatures to move through.', 3),
	(38, 'Fluoroantimonic Acid', 5, 2, 'A new and improved goo recipe with very aggressive properties makes every second in it more hellish!', 3),
	(39, 'Ingredient X', 5, 3, 'R&D mixed the goo with a nasty secret ingredient that melts away the plating of goo covered enemies in record time! ', 3),
	(40, 'Improved Alignment', 1, 1, 'Pin-point accuracy on first shot.', 4),
	(41, 'High Capacity Magazine', 1, 2, 'The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants.', 4),
	(42, 'Quickfire Ejector', 1, 3, 'Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster.', 4),
	(43, 'Expanded Ammo Bags', 2, 1, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 4),
	(44, 'Increased Caliber Rounds', 2, 2, 'The good folk in R&D have been busy. The overall damage of your weapon is increased.', 4),
	(45, 'Improved Propellant', 3, 1, 'The good folk in R&D have been busy. The overall damage of your weapon is increased.', 4),
	(46, 'Recoil Compensator', 3, 2, 'This little tweak reduces weapon recoil and spread per shot helping you hit consecutive shots.', 4),
	(47, 'Expanded Ammo Bags', 3, 3, 'You had to give up some sandwich-storage, but your total ammo capacity is increased!', 4),
	(48, 'Hollow-Point Bullets', 4, 1, 'Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome.', 4),
	(49, 'High Velocity Rounds', 4, 2, 'The Good folk in R&D have been busy. The overall damage of your weapon is increased.', 4),
	(50, 'Volatile Bullets', 5, 1, 'Bonus fire damage to burning targets.', 4),
	(51, 'Mactera Toxin-coating', 5, 2, 'Bonus damage against Mactera aliens', 4),
	(52, 'Increased Particle Density', 1, 1, 'Increased Particle Density', 5),
	(53, 'Larger Battery', 1, 2, 'Larger Battery', 5),
	(54, 'Higher Charged Plasma Energy', 1, 3, 'Higher Charged Plasma Energy', 5),
	(55, 'Heat Shield', 2, 1, 'Heat Shield', 5),
	(56, 'Overcharged Plasma Accelerator', 2, 2, 'Overcharged Plasma Accelerator', 5),
	(57, 'Improved Charge Efficiency', 3, 1, 'Improved Charge Efficiency', 5),
	(58, 'Crystal Capacitors', 3, 2, 'Crystal Capacitors', 5),
	(59, 'Tweaked Radiator', 3, 3, 'Tweaked Radiator', 5),
	(60, 'Expanded Plasma Splash', 4, 1, 'Expanded Plasma Splash', 5),
	(61, 'High Density Battery', 4, 2, 'High Density Battery', 5),
	(62, 'Reactive Shockwave', 4, 3, 'Reactive Shockwave', 5),
	(63, 'Flying Nightmare', 5, 1, 'Flying Nightmare', 5),
	(64, 'Thin Containment Field', 5, 2, 'Thin Containment Field', 5),
	(65, 'Plasma Burn', 5, 3, 'Plasma Burn', 5),
	(66, 'Barbed Drills', 1, 1, ' More damage inflicted on enemies ', 6),
	(67, 'Hardened Drill Tips', 1, 2, ' Drill faster. ', 6),
	(68, 'Expanded Fuel Tanks', 1, 3, ' Carries more fuel. ', 6),
	(69, 'Magnetic Refrigeration', 2, 1, ' Faster cooling for the drills when not in action ', 6),
	(70, 'Streamlined Integrity Check', 2, 2, ' Can use drills sooner after an overheat. ', 6),
	(71, 'Supercharged Motor', 3, 1, ' Drill faster. ', 6),
	(72, 'Increased Tank Pressure', 4, 1, ' Carries more fuel. ', 6),
	(73, 'Bloody Cold Drills', 4, 2, ' Your drills cool when drilling enemies! ', 6),
	(74, 'Fragmentary Shell', 1, 1, 'Larger damage radius', 7),
	(75, 'Extra Satchel Charge', 1, 2, 'Can carry one more explosive pack', 7),
	(76, 'Bigger Charge', 1, 3, 'More damage', 7),
	(77, 'Kill Switch', 2, 1, 'Disarm and pick up an unused charge', 7),
	(78, 'Extra Satchel Charge', 3, 1, 'Can carry one more explosive pack', 7),
	(79, 'Volatile Compound', 3, 2, 'More explosive power but the device will detonate if damaged', 7),
	(80, 'Big Bang', 4, 1, 'Chance to scare enemies far from the blast', 7),
	(81, 'Concussive Blast', 4, 2, 'Stuns enemies far from the blast', 7),
	(82, 'Rock Mover', 4, 3, 'Blast carves a much larger area', 7),
	(83, 'Improved Generator', 1, 1, ' Shield begins to regenerate sooner. ', 8),
	(84, 'Boosted Converter', 1, 2, ' Shield regenerates at a much faster rate but after a longer initial delay. ', 8),
	(85, 'Bigger Mineral Bag', 1, 3, ' You can collect more of each mineral before needing to deposit. ', 8),
	(86, 'Overcharger', 2, 1, ' Your shield can absorb more damage before breaking. ', 8),
	(87, 'Healthy', 2, 2, ' Max health increased. ', 8),
	(88, 'Temperature Insulation', 3, 1, ' For those who prefer it medium rare. Flames will inflict half as much damage. ', 8),
	(89, 'Shockwave', 4, 1, ' Your shield breaks violently, damaging all enemies around you in the process. ', 8),
	(90, 'Static Discharge', 4, 2, ' Whenever your shield breaks it releases a static discharge that has a chance to stun nearby enemies. ', 8),
	(91, 'Breathing Room', 4, 3, ' Temporary invulnerability after being revived. ', 8),
	(92, 'Supercharged Feed Mechanism', 1, 1, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 9),
	(93, 'Overstuffed Magazine', 1, 2, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 9),
	(94, 'Expanded Ammo Bags', 2, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 9),
	(95, 'Loaded Shells', 2, 2, ' More pellets in each shell ', 9),
	(96, 'Choke', 2, 3, ' Decreased shot spread ', 9),
	(97, 'Recoil Dampener', 3, 1, ' Quality engineering, the best lasercut parts, the tender loving care of a dedicated R&D Department. The recoil of your gun is drastically reduced. ', 9),
	(98, 'Quickfire Ejector', 3, 2, ' Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster. ', 9),
	(99, 'High Capacity Magazine', 3, 3, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 9),
	(100, 'Tungsten Coated Buckshot', 4, 1, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 9),
	(101, 'Bigger Pellets', 4, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 9),
	(102, 'Turret Whip', 5, 1, ' Shoot your turrets to make them create an overloaded shot ', 9),
	(103, 'Miner Adjustments', 5, 2, ' Fully automatic with an increased rate of fire ', 9),
	(104, 'Increased Caliber Rounds', 1, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 10),
	(105, 'Upgraded Capacitors', 1, 2, ' Better chance to electrocute target ', 10),
	(106, 'Expanded Ammo Bags', 1, 3, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 10),
	(107, 'High Capacity Magazine', 2, 1, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 10),
	(108, 'Recoil Dampener', 2, 2, ' Quality engineering, the best lasercut parts, the tender loving care of a dedicated R&D Department. The recoil of your gun is drastically reduced. ', 10),
	(109, 'Improved Gas System', 2, 3, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 10),
	(110, 'High Velocity Rounds', 3, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 10),
	(111, 'Expanded Ammo Bags', 3, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 10),
	(112, 'Hollow-Point Bullets', 4, 1, ' Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 10),
	(113, 'Conductive Bullets', 4, 2, ' More damage to targets that are in an electric field ', 10),
	(114, 'Magazine Capacity Tweak', 5, 1, ' Greatly increased magazine capacity ', 10),
	(115, 'Electric Arc', 5, 2, ' Chance for electrocution to arc from one target to others ', 10),
	(116, 'Increased Caliber Rounds', 1, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 11),
	(117, 'Expanded Ammo Bags', 1, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 11),
	(118, 'Macro Lens', 2, 1, ' The Macro Lens decreases the size of the lock on area for extra tight control and focused targeting while also greatly extending the lock on range. ', 11),
	(119, 'CCD Array Add-On', 2, 2, ' The CCD Array Add-On enables the camera to keep track of enemies in a wider angle and also expands the angle at which new locks can be acquired. ', 11),
	(120, 'Zoom Lens', 2, 3, ' The Zoom Lens increases the range of your camera, enabling you to lock on to targets farther away. ', 11),
	(121, 'Electro-Chemical Rounds', 3, 1, ' A simple copper wire and some reactive chemicals makes your rounds pack an extra punch with electricity and high temperatures. ', 11),
	(122, 'Smart Targeting Software', 3, 2, ' This premium software update makes your camera prioritize targets with lower health and avoids placing more locks necessary. Now that\'s SmÐ¯t(TM)! ', 11),
	(123, 'Super Blowthrough Rounds', 3, 3, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through an enemy! ', 11),
	(124, 'Shutter Speed Sensor', 4, 1, ' The shutter speed sensor reduces the time between lock ons, helping you reach a full lock on faster. ', 11),
	(125, 'Aperture Extension', 4, 2, ' The aperture extension helps the camera sort out more light and minimizes distortion, increasing the amount of lock ons you can place on targets. ', 11),
	(126, 'Electric Generator Mod', 5, 1, ' An electrical generator has been wired into the lock on mechanism, turning rounds electrical when a lock on threshold is passed. ', 11),
	(127, 'Unstable Lock Mechanism', 5, 2, ' Loosening a screw in the lock on mechanism bypasses the safety at a full lock on, making your rounds do more damage. ', 11),
	(128, 'Fear Frequency', 5, 3, ' Denting a cavity in the bullets cause them to emit a fear inducing high pitched sound when fired en masse affecting all enemies around the shooter. Both the strength of the effect and it\'s range are affected by how many rounds are fired in the burst. ', 11),
	(129, 'Fragmentary Shell', 1, 1, ' Damage radius increase ', 12),
	(130, 'Extra Ammo', 1, 2, ' Expanded Ammo Bags ', 12),
	(131, 'HE Compound', 1, 3, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 12),
	(132, 'Expanded Ammo Bags', 2, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 12),
	(133, 'Larger Payload', 2, 2, ' More bang for the buck! Increases the damage done within the Area of Effect! ', 12),
	(134, 'Incendiary Compound', 3, 1, ' 50% damage converted to heat. This will reduce direct damage, but will set enemies on fire. ', 12),
	(135, 'Pressure Wave', 3, 2, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 12),
	(136, 'High Velocity Grenades', 3, 3, ' We souped up the ejection mechanisms of your gun, so the projectiles are now fired at a much higher velocity. ', 12),
	(137, 'Homebrew Explosive', 4, 1, ' More damage on average but it\'s a bit inconsistent with a spread of 80% to 140% ', 12),
	(138, 'Nails + Tape', 4, 2, ' Fire in the hole! The Area of Effect is increased. (We advise keeping the term safe distance close to your heart) ', 12),
	(139, 'Concussive Blast', 4, 3, ' Stuns creatures within the blast radius ', 12),
	(140, 'Proximity Trigger', 5, 1, ' Launched grenades will only detonate when they are in close proximity to an enemy or after the projectile comes to a complete stop. Explosion range is also increased. Note: The trigger takes a moment to arm, indicated by a green light, and until then the grenade functions as usual. ', 12),
	(141, 'Spiky Grenade', 5, 2, ' Deals damage on direct impact ', 12),
	(142, 'Disabled Inertia Inhibitor', 5, 3, ' This tweak ensures that the user\'s velocity is transfered to the projectile. Usefull in high-speed applications but it requires doing more math in your head. ', 12),
	(143, 'Prolonged Power Generation', 1, 1, ' The projectile is able to travel for a longer period of time before collapsing ', 13),
	(144, 'High Capacity Magazine', 1, 2, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 13),
	(145, 'Expanded Ammo Bags', 2, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 13),
	(146, 'Condensed Plasma', 2, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 13),
	(147, 'Loosened Node Cohesion', 2, 3, ' Get a significantly wider plasma line that can hit more targets at once. ', 13),
	(148, 'Quick Deploy', 3, 1, ' The line projectile opens almost immediately and can hit multiple targets at very close range. ', 13),
	(149, 'Improved Case Ejector', 3, 2, ' A heavily preloaded spring combined with a smaller latch shorten the time it takes to reload. ', 13),
	(150, 'Armor Breaking', 4, 1, ' Greatly improves the armor breaking capabilities of the plasma beam. ', 13),
	(151, 'Disruptive Frequency Tuning', 4, 2, ' The plasma beam will stun most of the denizens of Hoxxes on contact. ', 13),
	(152, 'Explosive Goodbye', 5, 1, ' The projectile explodes at the end of its lifecycle when the nodes collapse damaging anything unlucky enough to be near by and leaving a residual plasma field for a short time. You can also manually trigger the explosion by pulling the trigger a second time while the projectile is in flight. ', 13),
	(153, 'Plasma Trail', 5, 2, 'The beam leaves behind a residual trail of plasma that will continuously damage any enemy that gets too close. ', 13),
	(154, 'Triple Split Line', 5, 3, 'The plasma beam is split into 3 lines that cover a taller area making it possible to hit multiple targets at various heights. ', 13),
	(155, 'Supercharged Feed Mechanism', 1, 1, 'We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 14),
	(156, 'Expanded Ammo Bags', 1, 2, 'You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 14),
	(157, 'High Capacity Magazine', 1, 3, 'The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 14),
	(158, 'Plastcrete MKII', 2, 1, 'Shock-absorbing compound reduces fall damage ', 14),
	(159, 'Expanded Ammo Bags', 3, 1, 'You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 14),
	(160, 'Repellant Additive', 3, 2, 'Enemies will avoid walking on the Plastcrete Foam whenever possible.', 14),
	(161, 'Disabled Inertia Inhibitor', 3, 3, 'This tweak ensures that the user\'s velocity is transfered to the projectile. Usefull in high-speed applications but it requires doing more math in your head. ', 14),
	(162, 'Gemini System', 1, 1, ' Can deploy two separate sentries at once. ', 15),
	(163, 'LMG MKII', 1, 2, ' An upgraded model with more punch, longer range and greater ammo capacity. ', 15),
	(164, 'Expanded Ammo Bags', 2, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 15),
	(165, 'Quick Deploy', 2, 2, ' Takes less time to build a sentry. ', 15),
	(166, 'Widemouth Refill Port', 2, 3, ' Refill a turret\'s ammo faster. ', 15),
	(167, 'Hardened Rounds', 3, 1, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 15),
	(168, 'Stun', 3, 2, ' Hit \'em so hard they can\'t recover! Every shot has a chance to stop the target in its tracks. ', 15),
	(169, 'Expanded Ammo Capacity', 3, 3, ' The sentry can fire more shots before refilling. ', 15),
	(170, 'Defender System', 4, 1, ' A design variation with greatly increased shot power and a focused scan angle. ', 15),
	(171, 'Hawkeye System', 4, 2, ' Upgraded sensors increase the effective range and target aquisition speed of the LMG and are synchronised with your laser pointer, prioritizing the target you highlight. ', 15),
	(172, 'Improved Generator', 1, 1, ' Shield begins to regenerate sooner. ', 16),
	(173, 'Boosted Converter', 1, 2, ' Shield regenerates at a much faster rate but after a longer initial delay. ', 16),
	(174, 'Bigger Mineral Bag', 1, 3, ' You can collect more of each mineral before needing to deposit. ', 16),
	(175, 'Overcharger', 2, 1, 'Your shield can absorb more damage before breaking. ', 16),
	(176, 'Healthy', 2, 2, 'Max health increased. ', 16),
	(177, 'Hazmat System', 3, 1, 'Reduces the damage taken from poison.', 16),
	(178, 'Shockwave', 4, 1, 'Your shield breaks violently, damaging all enemies around you in the process. ', 16),
	(179, 'Static Discharge', 4, 2, 'Whenever your shield breaks it releases a static discharge that has a chance to stun nearby enemies. ', 16),
	(180, 'Breathing Room', 4, 3, 'Temporary invulnerability after being revived. ', 16),
	(181, 'Magnetic Refrigeration', 1, 1, ' Increases the cooling rate and cooldown begins almost immediatly after you stop firing. ', 17),
	(182, 'Improved Motor', 1, 2, ' Increased rate of fire and faster gyro stabilization ', 17),
	(183, 'Improved Platform Stability', 1, 3, ' Increased Accuracy ', 17),
	(184, 'Oversized Drum', 2, 1, ' Expanded Ammo Bags ', 17),
	(185, 'High Velocity Rounds', 2, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 17),
	(186, 'Hardened Rounds', 3, 1, ' Improved armor breaking ', 17),
	(187, 'Improved Stun', 3, 2, ' Stun enemies more often and for a longer time! ', 17),
	(188, 'Blowthrough Rounds', 3, 3, ' Shaped bullets capable of passing through a target! ', 17),
	(189, 'Variable Chamber Pressure', 4, 1, ' Damage increase when fully stabilized ', 17),
	(190, 'Lighter Barrel Assembly', 4, 2, ' Start killing things sooner with a shorter spinup time ', 17),
	(191, 'Magnetic Bearings', 4, 3, ' Barrels keep spinning for a longer time after firing, keeping the gun stable for longer ', 17),
	(192, 'Aggressive Venting', 5, 1, ' Burn everything around you and send enemies running when the minigun overheats. The extreme heat dumping method also helps to significantly shorten downtime. ', 17),
	(193, 'Cold As The Grave', 5, 2, ' Every kill cools the gun ', 17),
	(194, 'Hot Bullets', 5, 3, ' Rounds fired when the heat meter is red will burn the target ', 17),
	(195, 'Increased Caliber Rounds', 1, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 18),
	(196, 'High Capacity Magazine', 1, 2, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 18),
	(197, 'Expanded Ammo Bags', 1, 3, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 18),
	(198, 'Tighter Barrel Alignment', 2, 1, ' Improved accuracy ', 18),
	(199, 'Improved Gas System', 2, 2, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 18),
	(200, 'Lighter Barrel Assembly', 2, 3, ' Reach the max rate of fire faster ', 18),
	(201, 'Supercharged Feed Mechanism', 3, 1, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 18),
	(202, 'Loaded Rounds', 3, 2, ' Increased splash damage ', 18),
	(203, 'High Velocity Rounds', 3, 3, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 18),
	(204, 'Hardened Rounds', 4, 1, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 18),
	(205, 'Shrapnel Rounds', 4, 2, ' Greater splash damage radius ', 18),
	(206, 'Feedback Loop', 5, 1, ' Increased damage when at max rate of fire ', 18),
	(207, 'Suppressive Fire', 5, 2, ' Chance to scare creatures next to a bullet impact ', 18),
	(208, 'Damage Resistance At Full RoF', 5, 3, ' Take significantly less damage when at max rate of fire. ', 18),
	(209, 'Missile Belt', 1, 1, ' Extra missiles stored in fancy belts. One for each shoulder! ', 19),
	(210, 'Pressurized Gas Cylinders', 1, 2, ' With gas cylinders filled to the brim your missiles really pack a punch! ', 19),
	(211, 'Increased Blast Radius', 1, 3, ' R&D improved the fuel consumption rate of your missiles, leaving more fuel on impact and a bigger explosion. ', 19),
	(212, 'Bigger Jet Engine', 2, 1, ' The engines in your missiles have been replaced with a more powerful variant, increasing their max velocity and turn rate. ', 19),
	(213, 'Anti-Tank Missiles', 2, 2, ' These anti-tank missiles will crack those big bugs\' plating like an egg ', 19),
	(214, 'Nano Missles', 3, 1, ' Half the size, but just as lethal. Your magazines can store a lot more missiles now. ', 19),
	(215, 'Improved Feed Mechanism', 3, 2, ' R&D improved the feed mechanism of this bad boy, making it fire faster! ', 19),
	(216, 'Shrapnel Load', 4, 1, ' R&D packed a little surprise in the missile heads that will tear those creature\'s fleshy bits to shreds. ', 19),
	(217, 'Zip Fuel', 4, 2, ' With this high energy fuel the impact force of your missiles hit like a truck. ', 19),
	(218, 'Napalm-Infused Rounds', 5, 1, ' 33% damage converted to heat. This will reduce direct damage, but can set enemies on fire. ', 19),
	(219, 'Uncontrolled Decompression', 5, 2, ' R&D furiously hit each missile with a wrench to give the impact shockwaves some more oomph. ', 19),
	(220, 'Nitroglycerin Rounds', 5, 3, ' With a pinch of nitroglycerin added to the fuel your missiles become ticking time-bombs, doing increased damage the longer they stay in the air. ', 19),
	(221, 'Quickfire Ejector', 1, 1, ' Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster. ', 20),
	(222, 'Perfect Weight Balance', 1, 2, ' Improved Accuracy ', 20),
	(223, 'Increased Caliber Rounds', 2, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 20),
	(224, 'Floating Barrel', 2, 2, ' Sweet, sweet optimization. We called in a few friends and managed to significantly improve the stability of this gun. ', 20),
	(225, 'Expanded Ammo Bags', 2, 3, ' Expanded Ammo Bags ', 20),
	(226, 'Super Blowthrough Rounds', 3, 1, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through several enemies at once! ', 20),
	(227, 'Explosive Rounds', 3, 2, ' Bullet detonates creating a radius of damage but deals less direct damage. ', 20),
	(228, 'Hollow-Point Bullets', 3, 3, ' Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 20),
	(229, 'Expanded Ammo Bags', 4, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 20),
	(230, 'High Velocity Rounds', 4, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 20),
	(231, 'Dead-Eye', 5, 1, ' No aim penalty while moving ', 20),
	(232, 'Neurotoxin Coating', 5, 2, ' Chance to poison your target. Affected creatures move slower and take damage over time. ', 20),
	(233, 'High Velocity Rounds', 1, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 21),
	(234, 'Floating Barrel', 1, 2, ' Sweet, sweet optimization. We called in a few friends and managed to significantly improve the stability of this gun. ', 21),
	(235, 'Blowthrough Rounds', 1, 3, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through an enemy! ', 21),
	(236, 'Recoil Dampener', 2, 1, ' Quality engineering, the best lasercut parts, the tender loving care of a dedicated R&D Department. The recoil of your gun is drastically reduced. ', 21),
	(237, 'Quickfire Ejector', 2, 2, ' Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster. ', 21),
	(238, 'Disabled Safety', 2, 3, ' Shorter delay between bursts ', 21),
	(239, 'High Capacity Magazine', 3, 1, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 21),
	(240, 'Increased Caliber Rounds', 3, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 21),
	(241, 'Hardened Rounds', 4, 1, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 21),
	(242, 'Expanded Ammo Bags', 4, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 21),
	(243, 'Hollow-Point Bullets', 4, 3, ' Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 21),
	(244, 'Burst Stun', 5, 1, ' Stun target if all shots in a burst hit ', 21),
	(245, 'Longer Burst', 5, 2, ' More bullets, faster! Fire more rounds at a higher rate in each burst. ', 21),
	(246, 'Expanded Ammo Bags', 1, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 22),
	(247, 'Upgraded Connection Joint', 1, 2, ' Increases the operational angle of the zipline ', 22),
	(248, 'Reinforced Anchor', 1, 3, ' Zipline can span a greater distance ', 22),
	(249, 'Reinforced Cable', 2, 1, ' Zipline can span a greater distance ', 22),
	(250, 'Disconnection Protection', 3, 1, ' Take less damage if you fall off the zipline ', 22),
	(251, 'Increased Motor Traction', 3, 2, ' Improved acceleration and speed when riding Ziplines. ', 22),
	(252, 'Streamlined Integrity Check', 1, 1, ' Generator recharges faster ', 23),
	(253, 'Improved Projector', 1, 2, ' Shield protects a larger area ', 23),
	(254, 'Fast Charging Capacitors', 2, 1, ' Generator recharges faster ', 23),
	(255, 'Larger Capacitors', 2, 2, ' Shield lasts longer ', 23),
	(256, 'Supercharged Coils', 3, 1, ' Shield protects a larger area ', 23),
	(257, 'Lasting Effect', 3, 2, ' The shield\'s protective properties linger for a few seconds after you leave the shield. ', 23),
	(258, 'Improved Efficiency', 3, 3, ' Shield lasts longer ', 23),
	(259, 'Improved Generator', 1, 1, ' Shield begins to regenerate sooner. ', 24),
	(260, 'Boosted Converter', 1, 2, ' Shield regenerates at a much faster rate but after a longer initial delay. ', 24),
	(261, 'Bigger Mineral Bag', 1, 3, ' You can collect more of each mineral before needing to deposit. ', 24),
	(262, 'Overcharger', 2, 1, ' Your shield can absorb more damage before breaking. ', 24),
	(263, 'Healthy', 2, 2, ' Max health increased. ', 24),
	(264, 'Reactive Armor', 3, 1, ' Fire in the hole! Fancy Reactive Armor plating takes half the sting out of any explosions. ', 24),
	(265, 'Shockwave', 4, 1, ' Your shield breaks violently, damaging all enemies around you in the process. ', 24),
	(266, 'Static Discharge', 4, 2, ' Whenever your shield breaks it releases a static discharge that has a chance to stun nearby enemies. ', 24),
	(267, 'Breathing Room', 4, 3, ' Temporary invulnerability after being revived. ', 24),
	(268, 'Gyro Stabilisation', 1, 1, ' Base accuracy improvement with pin-point accuracy on first shot. ', 25),
	(269, 'Supercharged Feed Mechanism', 1, 2, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 25),
	(270, 'Increased Caliber Rounds', 2, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 25),
	(271, 'Expanded Ammo Bags', 2, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 25),
	(272, 'Floating Barrel', 3, 1, ' Sweet, sweet optimization. We called in a few friends and managed to significantly improve the stability of this gun. ', 25),
	(273, 'Improved Propellant', 3, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 25),
	(274, 'High Capacity Magazine', 3, 3, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 25),
	(275, 'Hollow-Point Bullets', 4, 1, ' Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 25),
	(276, 'Hardened Rounds', 4, 2, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 25),
	(277, 'Improved Gas System', 4, 3, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 25),
	(278, 'Battle Frenzy', 5, 1, ' Move faster for a short time after killing an enemy ', 25),
	(279, 'Battle Cool', 5, 2, ' Killing an enemy increases accuracy ', 25),
	(280, 'Stun', 5, 3, ' Increased chance to stun the target on a weakpoint hit ', 25),
	(281, 'Expanded Ammo Bags', 1, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 26),
	(282, 'Increased Caliber Rounds', 1, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 26),
	(283, 'Fast-Charging Coils', 2, 1, ' Focus faster when holding down the trigger. ', 26),
	(284, 'Better Weight Balance', 2, 2, ' Improved hip-shot accuracy ', 26),
	(285, 'Hardened Rounds', 2, 3, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 26),
	(286, 'Killer Focus', 3, 1, ' Greater focus damage bonus ', 26),
	(287, 'Extended Clip', 3, 2, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 26),
	(288, 'Super Blowthrough Rounds', 4, 1, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through several enemies at once! ', 26),
	(289, 'Hollow-Point Bullets', 4, 2, ' Hit \'em where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 26),
	(290, 'Hitting Where it Hurts', 5, 1, ' Focused shots stagger the target ', 26),
	(291, 'Precision Terror', 5, 2, ' Killing your target with a focused shot to the weakspot will send nearby creatures fleeing with terror! ', 26),
	(292, 'Killing Machine', 5, 3, ' You can perform a lightning-fast reload right after killing an enemy. ', 26),
	(293, 'High-Volume Plasma Field', 1, 1, ' We overclocked your gun. It fires faster. Don\'t Ask. Just Enjoy. Also probably don\'t tell Management, please. ', 27),
	(294, 'Heat Shield', 1, 2, ' Less heat generated per shot. ', 27),
	(295, 'Stronger Plasma Accelerator', 1, 3, ' Launches the plasma projectiles at a higher velocity. ', 27),
	(296, 'Larger Battery', 2, 1, ' The good thing about clips, magazines, ammo drums, fuel tanks... you can always get bigger variants. ', 27),
	(297, 'Increased Caliber Rounds', 2, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 27),
	(298, 'Custom Coil Alignment', 3, 1, ' Hand-aligned coils with a custom two phase acceleration profile improves accuracy and reduces spread. ', 27),
	(299, 'Gen 2 Cooling System', 3, 2, ' The new and improved passive cooling system sheds heat faster when not firing. ', 27),
	(300, 'Hot Feet', 3, 3, ' The burning hot gases motivate you to move faster while the weapon is overheated. ', 27),
	(301, 'Overcharged PCF', 4, 1, ' The projectiles carry excess charge distributed across the containment field giving a small chance to electrocute the target on impact. ', 27),
	(302, 'Plasma Splash', 4, 2, ' A simple modification to the containment field causes it to rupture outward on impact damaging all things in a small radius even through heavy armor. ', 27),
	(303, 'Destructive Resonance AMP', 4, 3, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 27),
	(304, 'Manual Heat Dump', 5, 1, ' Pressing the reload button will force the DRAK-25 into overheat mode letting you quickly cool the weapon. ', 27),
	(305, 'Thermal Feedback Loop', 5, 2, ' Pumping excess heat back into the system results in a faster rate of fire when the weapon passes 50% heat. ', 27),
	(306, 'Expanded Ammo Bags', 1, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 28),
	(307, 'Double-Sized Buckshot', 1, 2, ' Bigger and heavier handcrafted specialist dwarf buckshot. Accept no substitute. ', 28),
	(308, 'Double Trigger', 2, 1, ' Tweaked trigger mechanism allows you to unload both barrels in quick succession dealing massive damage to anything infront of you. ', 28),
	(309, 'Quickfire Ejector', 2, 2, ' Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster. ', 28),
	(310, 'Improved Stun', 3, 1, ' Stun enemies more often and for a longer time! ', 28),
	(311, 'Expanded Ammo Bags', 3, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 28),
	(312, 'High Capacity Shells', 3, 3, ' It took some creative thinking, but we finally found out how to pack more buckshot into each shell. Just...handle with care, they\'re liable to take your eye out. ', 28),
	(313, 'Super Blowthrough Rounds', 4, 1, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through several enemies at once! ', 28),
	(314, 'Tungsten Coated Buckshot', 4, 2, ' We\'re proud of this one. Armor shredding. Tear through that high-impact plating of those big buggers like butter. What could be finer? ', 28),
	(315, 'Improved Blast Wave', 4, 3, ' The shockwave from the blast deals extra damage to any enemies unlucky enough to be in the area extending 4m in front of you. ', 28),
	(316, 'Auto Reload', 5, 1, ' Reloads automatically when unequipped for longer than 5 seconds ', 28),
	(317, 'Fear The Boomstick', 5, 2, ' Chance to scare nearby creatures whenever you shoot ', 28),
	(318, 'White Phosphorous Shells', 5, 3, ' Convert some of the damage to Fire damage ', 28),
	(319, 'Expanded Ammo Bags', 1, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased ', 29),
	(320, 'High Velocity Rounds', 1, 2, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 29),
	(321, 'High Capacity Magazine', 2, 1, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 29),
	(322, 'Supercharged Feed Mechanism', 2, 2, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 29),
	(323, 'Quickfire Ejector', 2, 3, ' Experience, training, and a couple of under-the-table design adjustments means your gun can be reloaded significantly faster. ', 29),
	(324, 'Increased Caliber Rounds', 3, 1, ' The good folk in R&D have been busy. The overall damage of your weapon is increased. ', 29),
	(325, 'Better Weight Balance', 3, 2, ' Base accuracy increase ', 29),
	(326, 'Blowthrough Rounds', 4, 1, ' Shaped projectiles designed to over-penetrate targets with a minimal loss of energy. In other words: Fire straight through an enemy! ', 29),
	(327, 'Hollow-Point Bullets', 4, 2, ' Hit em\' where it hurts! Literally! We\'ve upped the damage you\'ll be able to do to any creature\'s fleshy bits. You\'re welcome. ', 29),
	(328, 'Expanded Ammo Bags', 4, 3, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 29),
	(329, 'Conductive Bullets', 5, 1, ' More damage to targets that are in an electric field ', 29),
	(330, 'Get In, Get Out', 5, 2, ' Temporary movement speed bonus after emptying clip ', 29),
	(331, 'Improved Recharger', 1, 1, ' Spend less time waiting and more time swinging ', 30),
	(332, 'Longer Cable', 1, 2, ' Increased range ', 30),
	(333, 'Greater Cable Stretch', 2, 1, ' Increased range ', 30),
	(334, 'High Velocity Ejection System', 3, 1, ' Hook shoots out at a higher speed ', 30),
	(335, 'Overcharged Winch', 3, 2, ' Faster hook retraction means a faster dwarf. Survival not guaranteed. ', 30),
	(336, 'Safety First', 4, 1, ' Temporary * fall damage reduction bonus after releasing the Grappling Gun ', 30),
	(337, 'Momentum', 4, 2, ' Burst of Speed! Using the Grappling Gun gives you a Temporary Movement Speed Bonus when you land. ', 30),
	(338, 'Bypassed Integrity Check', 4, 3, ' Faster cooldown and a voided warranty ', 30),
	(339, 'Expanded Ammo Bags', 1, 1, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 31),
	(340, 'Thicker Core', 1, 2, ' More core material for a longer burn ', 31),
	(341, 'Supercharged Feed Mechanism', 2, 1, ' We overclocked your gun. It fires faster. Don\'t ask. Just enjoy. Also probably don\'t tell Management, please. ', 31),
	(342, 'High Capacity Magazine', 2, 2, ' The good thing about clips, magazines, ammo drums, fuel tanks ...you can always get bigger variants. ', 31),
	(343, 'Auto Reload', 3, 1, ' Reloads automatically when unequipped for longer than 5 seconds ', 31),
	(344, 'Expanded Ammo Bags', 3, 2, ' You had to give up some sandwich-storage, but your total ammo capacity is increased! ', 31),
	(345, 'Magnesium Core', 3, 3, ' A solid magnesium core is added to the flare, increasing how long it can burn ', 31),
	(346, 'Improved Generator', 1, 1, ' Shield begins to regenerate sooner. ', 32),
	(347, 'Boosted Converter', 1, 2, ' Shield regenerates at a much faster rate but after a longer initial delay. ', 32),
	(348, 'Bigger Mineral Bag', 1, 3, ' You can collect more of each mineral before needing to deposit. ', 32),
	(349, 'Overcharger', 2, 1, ' Your shield can absorb more damage before breaking. ', 32),
	(350, 'Healthy', 2, 2, ' Max health increased. ', 32),
	(351, 'Shock Absorbers', 3, 1, ' Built-in shock absorbers make falling less painful. ', 32),
	(352, 'Shockwave', 4, 1, ' Your shield breaks violently, damaging all enemies around you in the process. ', 32),
	(353, 'Static Discharge', 4, 2, ' Whenever your shield breaks it releases a static discharge that has a chance to stun nearby enemies. ', 32),
	(354, 'Breathing Room', 4, 3, ' Temporary invulnerability after being revived. ', 32);
/*!40000 ALTER TABLE `upgrade` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
